package gosqlfmt

var (
	SELECT    = "SELECT"
	FROM      = "FROM"
	WHERE     = "WHERE"
	AS        = "AS"
	GROUPBY   = "GROUP BY"
	ORDERBY   = "ORDER BY"
	HAVING    = "HAVING"
	PARTITION = "PARTITION BY"
	OVER      = "OVER"
	ASC       = "ASC"
	DESC      = "DESC"
	JOIN      = "JOIN"
	FULLJOIN  = "FULL OUTER JOIN"
	INNERJOIN = "INNER JOIN"
	LEFTJOIN  = "LEFT JOIN"
	RIGHJOIN  = "RIGHT JOIN"

	KEYWORDS = []string{SELECT, FROM, WHERE, AS, GROUPBY, ORDERBY, HAVING, PARTITION, OVER, ASC, DESC, JOIN, FULLJOIN, INNERJOIN, LEFTJOIN, RIGHJOIN}
)
